Rails.application.routes.draw do
  get "dashboards/show"
  resources :batches
  resources :inventory_items
  resources :recipes
  get "users/new"
  get "users/create"
  resources :passwords, param: :token
  resources :ingredients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

Rails.application.routes.draw do
  get "dashboards/show"
  resources :batches
  resources :inventory_items
  resources :recipes
  get "users/new"
  get "users/create"
  resources :passwords, param: :token
  # Existing authentication routes (generated by rails generate authentication)
  resource :session
  #user registration:
  resources :users, only: [:new, :create]
  # The root route is the "homepage" of your application.
  # By setting it to dashboards#show, users will see their dashboard
  # immediately after logging in.
  root "dashboards#show"
  
  # Your other routes
  resources :ingredients
  # New Week 4 resources
  resources :inventory_items
  resources :batches, only: [:index, :show, :new, :create, :destroy]
  
end